#!/bin/bash
chmod 755 MIUI-scripts/*
while :
do
clear
echo "===================================================="
echo "       MIUI v4 auto builder - by WFSdev Team        "
echo "===================================================="
echo "  1 - Update current MIUI ROM"
echo "  2 - Reodex current MIUI ROM"
echo "  3 - About"
echo "  4 - Exit"
    
echo -n "Please enter an option: "
  read opt

case $opt in
      1) clear; MIUI-scripts/upgrade;;
      2) clear; MIUI-scripts/reodex;;
      3) clear; MIUI-scripts/about;;
      4) clear; exit 1;;
      *) echo "Invalid Option"; continue;;
esac
scripts/press_enter
done